# Generated by Django 5.2.3 on 2025-06-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(default='new', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
