# Generated by Django 5.2.3 on 2025-06-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
